### ISSUE TITLE
Changes in 2020

### ISSUE THREAD

**Issue by markuskappe** [ginseng666/GeoJSON-TopoJSON-Austria#4]
In January 2020 some borders changed in Styria. I've got up-to-date .shp files, but don't know how to convert them to TopoJSON. Can you help? Thank you!

**Comment by ginseng666** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Just go to https://mapshaper.org/ , upload the shps and export as topojson, that should work.
 
 

markuskappe schrieb am 09.09.2020 15:41 (GMT +02:00):

In January 2020 some borders changed in Styria. I've got up-to-date .shp files,
but don't know how to convert them to TopoJSON. Can you help? Thank you!

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/issues/4

**Comment by markuskappe** [comment]
Thank you!
